export const Paths = {
  home: "/",
  auth: "/auth",
  user: "/user",
  booking: "/booking",
  service: "/service",
  client: "/client",
  category: "/category",
  review: "/review",
  about_us: "/about_us",
  admin: "/admin",
  branch: "/branch",
  forgotPassword: "/forgot-password",
  resetPassword: "/user/reset-password",
  AdminService: "/admin/service",
  AdminCategory: "/admin/category",
  AdminUser: "/admin/user",
  AdminClient: "/admin/client",
  AdminReview: "/admin/review",
  AdminBooking: "/admin/booking",
  AdminMasterAvailability: "/admin/masterAvailability",
  MasterAvailability: "/admin/Availability",
  userBooking: "/user/all-bookings",
  AdminAllBookings: "/admin/all-bookings",
  AdminBranch: "/admin/branch",
} as const
