module.exports = {
  ERRORS: {
    BOOKING_NOT_FOUND: "Booking не знайдено",
    CATEGORY_NOT_FOUND: "Категорію не знайдено",
    USER_NOT_FOUND: "користувач не знайдено",
    SERVICE_NOT_FOUND: "Послугу не знайдено",
    SERVER_NOT_FOUND: "сервер не знайдено",
    REVIEW_NOT_FOUND: "відгук не знайдено",
    CLIENT_NOT_FOUND: "клієнт не знайдено",
    NAME_EMPTY: "Назва не може бути порожньою",
    USER_EMPTY: "Користувач не може бути порожнім",
    CLIENT_EMPTY: "Клієнт не може бути порожнім",
    SERVICE_EMPTY: "Послуга не може бути порожнім",
    REVIEW_EMPTY: "Відгук не може бути порожнім",
    CATEGORY_EMPTY: "Категорія не може бути порожньою",
    TEST_ERROR: "Test error",
    NAME_REQUIRED: "Назва обов'язкове для заповнення",
    AUTH_REQUIRED: "Не автентифікований",
    USER_REQUIRED: "Користувач обов'язкове для заповнення",
    NAME_ALL_REQUIRED: "Поля обов'язкові для заповнення",
    SERVICE_REQUIRED: "Послуга обов'язкова для заповнення",
    DATE_REQUIRED: "Дата обов'язкова для заповнення",
    DATE_FORMAT: "Введіть правильний формат ISO дати",
    LOGIN_FORMAT: "Невірний формат даних",
    PHONE_REQUIRED: "Номер телефону обов'язковий для заповнення",
    PHONE_EMPTY: "Номер телефону не може бути порожнім",
    PHONE_FORMAT_INVALID: "Невірний формат номеру телефону",
    RATING_REQUIRED: "Оцінка обов'язкова для заповнення",
    RATING_MIN: "Оцінка має бути від 1",
    RATING_MAX: "Оцінка має бути до 5",
    PRICE_REQUIRED: "Ціна обов'язкова для заповнення",
    PRICE_EMPTY: "Ціна не може бути порожньою",
    DURATION_REQUIRED: "Тривалість обов'язкова для заповнення",
    DURATION_EMPTY: "Тривалість не може бути порожньою",
    INVALID_PAGE_OR_LIMIT: "Неправильний номер сторінки або ліміту",
    SERVICE_DELETED: "Послугу видалено",
    EMAIL_OR_PASSWORD_REQUIRED: "Email або пароль обов'язкові для заповнення",
    INVALID_EMAIL_OR_PASSWORD: "Не правильно введений пароль або логін",
    USER_ALREADY_EXISTS: "Користувач з таким email вже існує",
    JWT_SECRET_NOT_FOUND: "JWT_SECRET не знайдено",
    USER_NOT_REFRESH: "Не вдалося оновити користувача",
    USER_DELETED: "Користувача видалено",
    USER_NOT_DELETED: "Не вдалося видалити користувача",
    ACCESS_DENIED: "Доступ заборонено",
  },
};
